spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#oracl용 테스트
#    spring:
#      datasource:
#        url: jdbc:h2:mem:testdb;MODE=Oracle
#        username: sa
#        password:
#        driver-class-name: org.h2.Driver


